In [6]:
 import sys
 print(sys.executable)

/home/joao/code/random-scripts/.venv/bin/python

In [11]:
import pandas as pd

In [16]:
def format_dfev(df):
    df = df.loc[df['isin'].str.startswith('BR', na=False)]

    # cols
    df['ticker'] = df['ticker'].str.split().str[0]
    df['weight%'] = df['weight'] * 100
    df['weight_br%'] = df['principal'] / df['principal'].sum()
    df['weight_br%'] = (df['weight_br%'] * 100).round(2)
    df['shares'] = (df['shares'] / 100).fillna(0).astype(int)
    df['principal'] = df['principal'].fillna(0).astype(int)
    df = df.drop(['etf_ticker','coupon_rate', 'maturity_date', 'sedol', 'identifier', 'weight'], axis=1)
    
    return df.sort_values(by='market_value', ascending=False) \
        .reset_index(drop=True)

In [18]:
dfs = [
    # pd.read_excel("~/Downloads/etfs/DFEV 23-12-01.xlsx"),
    # pd.read_csv("~/Downloads/etfs/DFEV 24-06-18.csv"),
    # pd.read_csv("~/Downloads/etfs/DFEV 24-07-23.csv"),
    # pd.read_csv("~/Downloads/etfs/DFEV 24-08-30.csv"),
    # pd.read_csv("~/Downloads/etfs/DFEV 24-10-23.csv"),
    # pd.read_csv("~/Downloads/etfs/DFEV 24-12-11.csv"),
    # pd.read_csv("~/Downloads/etfs/DFEV 25-01-02.csv"),
    # pd.read_csv("~/Downloads/etfs/DFEV 25-03-20.csv"),
    # pd.read_csv("~/Downloads/etfs/DFEV 25-06-16.csv"),
    # pd.read_csv("~/Downloads/etfs/DFEV 25-07-24.csv"),
    # pd.read_csv("~/Downloads/etfs/DFEV 25-08-07.csv"),
    # pd.read_csv("~/Downloads/etfs/DFEV 25-09-18.csv"),
    pd.read_csv("~/Downloads/etfs/DFEV 25-12-03.csv"),
    pd.read_csv("~/Downloads/etfs/DFEV 26-01-22.csv"),
    pd.read_csv("~/Downloads/etfs/DFEV 26-05-06.csv"),

]

df_old = format_dfev(dfs[-2])
df_new = format_dfev(dfs[-1])

print(df_new.to_string())

          date  ticker                description  market_value          isin  shares  principal   weight%  weight_br%
0   2026-05-06   PETR4     PETROLEO BRASILEIRO SA    8612552.04  BRPETRACNPR6    8970   42402608  0.451604       21.48
1   2026-05-06   PETR3     PETROLEO BRASILEIRO SA    7248588.31  BRPETRACNOR9    6926   35687337  0.380083       18.08
2   2026-05-06  SANB11  BANCO SANTANDER BRASIL SA    4340817.36  BRSANBCDAM13    7286   21371363  0.227613       10.83
3   2026-05-06   BBDC4          BANCO BRADESCO SA    2385298.28  BRBBDCACNPR8    6094   11743658  0.125074        5.95
4   2026-05-06   VBBR3           VIBRA ENERGIA SA    1811236.30  BRVBBRACNOR1    2716    8917350  0.094973        4.52
5   2026-05-06   BBAS3         BANCO DO BRASIL SA    1487366.53  BRBBASACNOR3    3318    7322826  0.077991        3.71
6   2026-05-06   LREN3            LOJAS RENNER SA    1209387.71  BRLRENACNOR1    4053    5935508  0.063415        3.01
7   2026-05-06   BBDC3          BANCO BRADESCO SA     855866.55  BRBBDCACNOR1    2532    4213730  0.044878        2.13
8   2026-05-06   COGN3             COGNA EDUCACAO     686920.54  BRCOGNACNOR2   12035    3351496  0.036019        1.70
9   2026-05-06   EMBJ3                 EMBRAER SA     622477.48  BREMBJACNOR1     365    3064674  0.032640        1.55
10  2026-05-06   HYPE3                  HYPERA SA     613246.62  BRHYPEACNOR0    1286    3004265  0.032156        1.52
11  2026-05-06   CYRE3  CYRELA BRAZIL REALTY SA E     590443.50  BRCYREACNOR7    1253    2906960  0.030960        1.47
12  2026-05-06   JHSF3      JHSF PARTICIPACOES SA     534155.00  BRJHSFACNOR2    2074    2629832  0.028009        1.33
13  2026-05-06   IRBR3  IRB BRASIL RESSEGUROS S/A     472786.63  BRIRBRACNOR4     435    2327694  0.024791        1.18
14  2026-05-06   BRAV3              BRAVA ENERGIA     435325.37  BRBRAVACNOR3    1181    2125912  0.022827        1.08
15  2026-05-06   BRSR6  BANCO DO ESTADO DO RIO GR     415066.73  BRBRSRACNPB4    1314    2043518  0.021764        1.04
16  2026-05-06   GGBR4                  GERDAU SA     400330.59  BRGGBRACNPR8     809    1970967  0.020992        1.00
17  2026-05-06   MGLU3          MAGAZINE LUIZA SA     341380.41  BRMGLUACNOR2    2093    1647460  0.017900        0.83
18  2026-05-06   VALE3                    VALE SA     294819.35  BRVALEACNOR0     178    1451498  0.015459        0.74
19  2026-05-06   CEAB3             C&A MODAS LTDA     291576.26  BRCEABACNOR1    1169    1435532  0.015289        0.73
20  2026-05-06   CSNA3   CIA SIDERURGICA NACIONAL     287037.10  BRCSNAACNOR6    2109    1413184  0.015051        0.72
21  2026-05-06   AZZA3              AZZAS 2154 SA     284773.14  BRAZZAACNOR9     627    1402037  0.014932        0.71
22  2026-05-06   DXCO3                   DEXCO SA     263745.27  BRDXCOACNOR8    2409    1298510  0.013830        0.66
23  2026-05-06   FLRY3                  FLEURY SA     248299.20  BRFLRYACNOR5     726    1222463  0.013020        0.62
24  2026-05-06   YDUQ3     YDUQS PARTICIPACOES SA     241934.71  BRYDUQACNOR3    1166    1191129  0.012686        0.60
25  2026-05-06   CBAV3  CIA BRASILEIRA DE ALUMINI     236418.99  BRCBAVACNOR5    1093    1163973  0.012397        0.59
26  2026-05-06   POMO4               MARCOPOLO SA     235028.56  BRPOMOACNPR7    1813    1157127  0.012324        0.59
27  2026-05-06   SMTO3            SAO MARTINHO SA     233957.22  BRSMTOACNOR3     681    1151853  0.012268        0.58
28  2026-05-06   PRIO3               PETRO RIO SA     218946.04  BRPRIOACNOR1     162    1077948  0.011481        0.55
29  2026-05-06   MOVI3    MOVIDA PARTICIPACOES SA     183160.77  BRMOVIACNOR0     745     874766  0.009604        0.44
30  2026-05-06   EZTC3   EZ TEC EMPREENDIMENTOS E     180080.64  BREZTCACNOR0     620     886600  0.009443        0.45
31  2026-05-06   VAMO3  VAMOS LOCACAO DE CAMINHOE     179105.49  BRVAMOACNOR7    2199     881799  0.009391        0.45
32  2026-05-06   RECV3          PETRORECONCAVO SA     176856.17  BRRECVACNOR3     688     842499  0.009274        0.43
33  2026-05-06   PGMN3  EMPREENDIMENTOS PAGUE MEN     158866.95  BRPGMNACNOR8    1484     782157  0.008330        0.40
34  2026-05-06   SBFG3               GRUPO SBF SA     155857.90  BRSBFGACNOR1     669     767343  0.008172        0.39
35  2026-05-06   SEER3         SER EDUCACIONAL SA     150177.22  BRSEERACNOR5     544     739375  0.007875        0.37
36  2026-05-06   GMAT3            GRUPO MATEUS SA     145423.55  BRGMATACNOR7    1580     715971  0.007625        0.36
37  2026-05-06   DASA3  DIAGNOSTICOS DA AMERICA S     136483.85  BRDASAACNOR1    1993     671957  0.007157        0.34
38  2026-05-06   ANIM3           ANIMA HOLDING SA     135794.73  BRANIMACNOR6    1611     668565  0.007120        0.34
39  2026-05-06   MDIA3           M DIAS BRANCO SA     133561.85  BRMDIAACNOR7     270     657571  0.007003        0.33
40  2026-05-06   RIAA3                  RIACHUELO     130936.05  BRRIAAACNOR2     637     644644  0.006866        0.33
41  2026-05-06   ABCB4        BANCO ABC BRASIL SA     128566.48  BRABCBACNPR4     250     632977  0.006741        0.32
42  2026-05-06   DESK3  DESKTOP - SIGMANET COMUNI     124892.21  BRDESKACNOR2     334     614888  0.006549        0.31
43  2026-05-06   GRND3                GRENDENE SA     123673.33  BRGRNDACNOR3    1396     608887  0.006485        0.31
44  2026-05-06   VLID3  VALID SOLUCOES E SERVICOS     116312.92  BRVLIDACNOR5     295     572649  0.006099        0.29
45  2026-05-06   INTB3  INTELBRAS SA INDUSTRIA DE     110439.43  BRINTBACNOR9     388     508031  0.005791        0.26
46  2026-05-06   LWSA3                    LWSA SA     109683.04  BRLWSAACNOR8    1350     540008  0.005751        0.27
47  2026-05-06   MDNE3  MOURA DUBEUX ENGENHARIA S     102984.68  BRMDNEACNOR9     164     507029  0.005400        0.26
48  2026-05-06   CYRE4  CYRELA BRAZIL REALTY SA E     102333.24  BRCYREACNPR4     237     503822  0.005366        0.26
49  2026-05-06   FESA4   CIA FERRO LIGAS DA BAHIA     100543.56  BRFESAACNPR5     637     495011  0.005272        0.25
50  2026-05-06  JBSS32                     JBS NV      86960.01  BRJBSSBDR002      52     428134  0.004560        0.22
51  2026-05-06   MYPK3           IOCHPE MAXION SA      85422.33  BRMYPKACNOR7     416     470408  0.004479        0.24
52  2026-05-06   BMOB3      BEMOBI MOBILE TECH SA      75243.08  BRBMOBACNOR7     137     370448  0.003945        0.19
53  2026-05-06   OPCT3  OCEANPACT SERVICOS MARITI      72873.61  BROPCTACNOR0     349     358782  0.003821        0.18
54  2026-05-06   BMGB4               BANCO BMG SA      67455.42  BRBMGBACNPR0     609     332106  0.003537        0.17
55  2026-05-06   LAVV3  LAVVI EMPREENDIMENTOS IMO      64850.97  BRLAVVACNOR4     252     319284  0.003400        0.16
56  2026-05-06   CSED3  CRUZEIRO DO SUL EDUCACION      63337.36  BRCSEDACNOR9     568     311832  0.003321        0.16
57  2026-05-06   RANI3  IRANI PAPEL E EMBALAGEM S      62048.56  BRRANIACNOR5     388     305486  0.003254        0.15
58  2026-05-06   EUCA4  EUCATEX SA INDUSTRIA E CO      62023.52  BREUCAACNPR8     141     305363  0.003252        0.15
59  2026-05-06   QUAL3  QUALICORP CONSULTORIA E C      59351.05  BRQUALACNOR6    1571     292206  0.003112        0.15
60  2026-05-06   BLAU3       BLAU FARMACEUTICA SA      57806.57  BRBLAUACNOR8     269     284602  0.003031        0.14
61  2026-05-06   EVEN3  EVEN CONSTRUTORA E INCORP      57075.96  BREVENACNOR8     473     281004  0.002993        0.14
62  2026-05-06   PNVL3  DIMED SA DISTRIBUIDORA DA      50074.74  BRPNVLACNOR9     174     246535  0.002626        0.12
63  2026-05-06   ALLD3       ALLIED TECNOLOGIA SA      48741.26  BRALLDACNOR3     379     239970  0.002556        0.12
64  2026-05-06   JSLG3                     JSL SA      47465.24  BRJSLGACNOR2     321     233688  0.002489        0.12
65  2026-05-06   MELK3  MELNICK EVEN DESENVOLVIME      46402.55  BRMELKACNOR8     684     228456  0.002433        0.12
66  2026-05-06   PFRM3  PROFARMA DISTRIBUIDORA DE      43645.89  BRPFRMACNOR1     282     214884  0.002289        0.11
67  2026-05-06   TRIS3                  TRISUL SA      43293.64  BRTRISACNOR4     445     213149  0.002270        0.11
68  2026-05-06   PINE4              BANCO PINE SA      39750.41  BRPINEACNPR8     137     195705  0.002084        0.10
69  2026-05-06   SHUL4                  SCHULZ SA      38175.23  BRSHULACNPR4     358     187950  0.002002        0.10
70  2026-05-06   FIQE3  UNIFIQUE TELECOMUNICACOES      37259.35  BRFIQEACNOR5     260     183440  0.001954        0.09
71  2026-05-06   AGRO3  BRASILAGRO - CO BRASILEIR      34635.77  BRAGROACNOR7      89     170524  0.001816        0.09
72  2026-05-06   ARML3  ARMAC LOCACAO LOGISTICA E      34396.09  BRARMLACNOR1     378     169344  0.001804        0.09
73  2026-05-06   CAML3         CAMIL ALIMENTOS SA      26353.60  BRCAMLACNOR3     199     129748  0.001382        0.07
74  2026-05-06   LJQQ3      LOJAS QUERO QUERO S/A      20313.61  BRLJQQACNOR5     507     100010  0.001065        0.05
75  2026-05-06   MATD3      HOSPITAL MATER DEI SA       9759.21  BRMATDACNOR4      84      48048  0.000512        0.02
76  2026-05-06   SLCE3            SLC AGRICOLA SA       7129.29  BRSLCEACNOR2      20      35100  0.000374        0.02
77  2026-05-06   POMO3               MARCOPOLO SA       1127.94  BRPOMOACNOR0       9       5553  0.000059        0.00
78  2026-05-06  PINE13              BANCO PINE SA          0.00  BRPINEN03M16       0          0  0.000000        0.00

/tmp/ipykernel_16059/2469391824.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ticker'] = df['ticker'].str.split().str[0]
/tmp/ipykernel_16059/2469391824.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weight%'] = df['weight'] * 100
/tmp/ipykernel_16059/2469391824.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weight_br%'] = df['principal'] / df['principal'].sum()
/tmp/ipykernel_16059/2469391824.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weight_br%'] = (df['weight_br%'] * 100).round(2)
/tmp/ipykernel_16059/2469391824.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['shares'] = (df['shares'] / 100).fillna(0).astype(int)
/tmp/ipykernel_16059/2469391824.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['principal'] = df['principal'].fillna(0).astype(int)
/tmp/ipykernel_16059/2469391824.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['ticker'] = df['ticker'].str.split().str[0]
/tmp/ipykernel_16059/2469391824.py:6: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weight%'] = df['weight'] * 100
/tmp/ipykernel_16059/2469391824.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weight_br%'] = df['principal'] / df['principal'].sum()
/tmp/ipykernel_16059/2469391824.py:8: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['weight_br%'] = (df['weight_br%'] * 100).round(2)
/tmp/ipykernel_16059/2469391824.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['shares'] = (df['shares'] / 100).fillna(0).astype(int)
/tmp/ipykernel_16059/2469391824.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['principal'] = df['principal'].fillna(0).astype(int)

In [19]:
# position change
share_ratio_col = 'share_ratio'
df_merged = pd.merge(df_new, df_old, on="ticker", suffixes=('_new', '_old'))
df_merged[share_ratio_col] = (df_merged.shares_new / df_merged.shares_old).round(2)
df_merged[df_merged[share_ratio_col] != 1].sort_values(by=share_ratio_col, ascending=False)

,date_new,ticker,description_new,market_value_new,isin_new,shares_new,principal_new,weight%_new,weight_br%_new,date_old,description_old,market_value_old,isin_old,shares_old,principal_old,weight%_old,weight_br%_old,share_ratio
14,2026-05-06,BRAV3,BRAVA ENERGIA,435325.37,BRBRAVACNOR3,1181,2125912,0.022827,1.08,2026-01-22,BRAVA ENERGIA,12005.96,BRBRAVACNOR3,35,63579,0.000851,0.04,33.74
45,2026-05-06,FESA4,CIA FERRO LIGAS DA BAHIA,100543.56,BRFESAACNPR5,637,495011,0.005272,0.25,2026-01-22,CIA FERRO LIGAS DA BAHIA,11611.42,BRFESAACNPR5,86,61490,0.000823,0.04,7.41
6,2026-05-06,LREN3,LOJAS RENNER SA,1209387.71,BRLRENACNOR1,4053,5935508,0.063415,3.01,2026-01-22,LOJAS RENNER SA,246420.29,BRLRENACNOR1,872,1304955,0.017460,0.83,4.65
35,2026-05-06,DASA3,DIAGNOSTICOS DA AMERICA S,136483.85,BRDASAACNOR1,1993,671957,0.007157,0.34,2026-01-22,DIAGNOSTICOS DA AMERICA S,41107.66,BRDASAACNOR1,507,217691,0.002913,0.14,3.93
40,2026-05-06,GRND3,GRENDENE SA,123673.33,BRGRNDACNOR3,1396,608887,0.006485,0.31,2026-01-22,GRENDENE SA,36479.93,BRGRNDACNOR3,405,72077,0.002585,0.05,3.45
57,2026-05-06,ALLD3,ALLIED TECNOLOGIA SA,48741.26,BRALLDACNOR3,379,239970,0.002556,0.12,2026-01-22,ALLIED TECNOLOGIA SA,22596.55,BRALLDACNOR3,140,119663,0.001601,0.08,2.71
21,2026-05-06,AZZA3,AZZAS 2154 SA,284773.14,BRAZZAACNOR9,627,1402037,0.014932,0.71,2026-01-22,AZZAS 2154 SA,123907.08,BRAZZAACNOR9,263,656168,0.008779,0.42,2.38
60,2026-05-06,PFRM3,PROFARMA DISTRIBUIDORA DE,43645.89,BRPFRMACNOR1,282,214884,0.002289,0.11,2026-01-22,PROFARMA DISTRIBUIDORA DE,22150.26,BRPFRMACNOR1,138,117300,0.001569,0.07,2.04
10,2026-05-06,HYPE3,HYPERA SA,613246.62,BRHYPEACNOR0,1286,3004265,0.032156,1.52,2026-01-22,HYPERA SA,304215.72,BRHYPEACNOR0,640,1611019,0.021555,1.02,2.01
24,2026-05-06,YDUQ3,YDUQS PARTICIPACOES SA,241934.71,BRYDUQACNOR3,1166,1191129,0.012686,0.60,2026-01-22,YDUQS PARTICIPACOES SA,148442.75,BRYDUQACNOR3,594,786100,0.010518,0.50,1.96
37,2026-05-06,MDIA3,M DIAS BRANCO SA,133561.85,BRMDIAACNOR7,270,657571,0.007003,0.33,2026-01-22,M DIAS BRANCO SA,70842.80,BRMDIAACNOR7,148,375158,0.005020,0.24,1.82
39,2026-05-06,DESK3,DESKTOP - SIGMANET COMUNI,124892.21,BRDESKACNOR2,334,614888,0.006549,0.31,2026-01-22,DESKTOP - SIGMANET COMUNI,65312.10,BRDESKACNOR2,189,345870,0.004628,0.22,1.77
59,2026-05-06,MELK3,MELNICK EVEN DESENVOLVIME,46402.55,BRMELKACNOR8,684,228456,0.002433,0.12,2026-01-22,MELNICK EVEN DESENVOLVIME,27837.94,BRMELKACNOR8,390,147420,0.001972,0.09,1.75
22,2026-05-06,DXCO3,DEXCO SA,263745.27,BRDXCOACNOR8,2409,1298510,0.013830,0.66,2026-01-22,DEXCO SA,165746.62,BRDXCOACNOR8,1521,877736,0.011744,0.56,1.58
29,2026-05-06,MOVI3,MOVIDA PARTICIPACOES SA,183160.77,BRMOVIACNOR0,745,874766,0.009604,0.44,2026-01-22,MOVIDA PARTICIPACOES SA,98090.51,BRMOVIACNOR0,477,519453,0.006950,0.33,1.56
55,2026-05-06,EVEN3,EVEN CONSTRUTORA E INCORP,57075.96,BREVENACNOR8,473,281004,0.002993,0.14,2026-01-22,EVEN CONSTRUTORA E INCORP,42601.72,BREVENACNOR8,304,225603,0.003019,0.14,1.56
19,2026-05-06,CEAB3,C&A MODAS LTDA,291576.26,BRCEABACNOR1,1169,1435532,0.015289,0.73,2026-01-22,C&A MODAS LTDA,166007.95,BRCEABACNOR1,792,879120,0.011762,0.56,1.48
36,2026-05-06,ANIM3,ANIMA HOLDING SA,135794.73,BRANIMACNOR6,1611,668565,0.007120,0.34,2026-01-22,ANIMA HOLDING SA,110298.07,BRANIMACNOR6,1180,584100,0.007815,0.37,1.37
8,2026-05-06,COGN3,COGNA EDUCACAO,686920.54,BRCOGNACNOR2,12035,3351496,0.036019,1.70,2026-01-22,COGNA EDUCACAO,726094.69,BRCOGNACNOR2,8839,3845143,0.051447,2.43,1.36
15,2026-05-06,BRSR6,BANCO DO ESTADO DO RIO GR,415066.73,BRBRSRACNPB4,1314,2043518,0.021764,1.04,2026-01-22,BANCO DO ESTADO DO RIO GR,332119.91,BRBRSRACNPB4,1002,1758790,0.023532,1.11,1.31
54,2026-05-06,QUAL3,QUALICORP CONSULTORIA E C,59351.05,BRQUALACNOR6,1571,292206,0.003112,0.15,2026-01-22,QUALICORP CONSULTORIA E C,55057.26,BRQUALACNOR6,1246,291564,0.003901,0.18,1.26
33,2026-05-06,SEER3,SER EDUCACIONAL SA,150177.22,BRSEERACNOR5,544,739375,0.007875,0.37,2026-01-22,SER EDUCACIONAL SA,93960.81,BRSEERACNOR5,436,497583,0.006658,0.31,1.25
30,2026-05-06,RECV3,PETRORECONCAVO SA,176856.17,BRRECVACNOR3,688,842499,0.009274,0.43,2026-01-22,PETRORECONCAVO SA,114397.07,BRRECVACNOR3,557,605806,0.008106,0.38,1.24
43,2026-05-06,MDNE3,MOURA DUBEUX ENGENHARIA S,102984.68,BRMDNEACNOR9,164,507029,0.005400,0.26,2026-01-22,MOURA DUBEUX ENGENHARIA S,64322.23,BRMDNEACNOR9,134,340628,0.004558,0.22,1.22
32,2026-05-06,SBFG3,GRUPO SBF SA,155857.90,BRSBFGACNOR1,669,767343,0.008172,0.39,2026-01-22,GRUPO SBF SA,147418.73,BRSBFGACNOR1,549,780678,0.010445,0.49,1.22
52,2026-05-06,CSED3,CRUZEIRO DO SUL EDUCACION,63337.36,BRCSEDACNOR9,568,311832,0.003321,0.16,2026-01-22,CRUZEIRO DO SUL EDUCACION,60189.78,BRCSEDACNOR9,466,318744,0.004265,0.20,1.22
23,2026-05-06,FLRY3,FLEURY SA,248299.20,BRFLRYACNOR5,726,1222463,0.013020,0.62,2026-01-22,FLEURY SA,187268.44,BRFLRYACNOR5,602,991708,0.013269,0.63,1.21
31,2026-05-06,PGMN3,EMPREENDIMENTOS PAGUE MEN,158866.95,BRPGMNACNOR8,1484,782157,0.008330,0.40,2026-01-22,EMPREENDIMENTOS PAGUE MEN,143369.48,BRPGMNACNOR8,1222,759234,0.010158,0.48,1.21
50,2026-05-06,BMGB4,BANCO BMG SA,67455.42,BRBMGBACNPR0,609,332106,0.003537,0.17,2026-01-22,BANCO BMG SA,46695.31,BRBMGBACNPR0,519,247282,0.003309,0.16,1.17
38,2026-05-06,ABCB4,BANCO ABC BRASIL SA,128566.48,BRABCBACNPR4,250,632977,0.006741,0.32,2026-01-22,BANCO ABC BRASIL SA,104698.67,BRABCBACNPR4,216,554447,0.007418,0.35,1.16
17,2026-05-06,MGLU3,MAGAZINE LUIZA SA,341380.41,BRMGLUACNOR2,2093,1647460,0.017900,0.83,2026-01-22,MAGAZINE LUIZA SA,309640.23,BRMGLUACNOR2,1830,1639746,0.021940,1.04,1.14
16,2026-05-06,GGBR4,GERDAU SA,400330.59,BRGGBRACNPR8,809,1970967,0.020992,1.00,2026-01-22,GERDAU SA,312533.27,BRGGBRACNPR8,717,1655066,0.022144,1.05,1.13
2,2026-05-06,SANB11,BANCO SANTANDER BRASIL SA,4340817.36,BRSANBCDAM13,7286,21371363,0.227613,10.83,2026-01-22,BANCO SANTANDER BRASIL SA,4345931.62,BRSANBCDAM13,6547,23014532,0.307930,14.56,1.11
28,2026-05-06,PRIO3,PETRO RIO SA,218946.04,BRPRIOACNOR1,162,1077948,0.011481,0.55,2026-01-22,PETRO RIO SA,131003.75,BRPRIOACNOR1,150,693750,0.009282,0.44,1.08
27,2026-05-06,SMTO3,SAO MARTINHO SA,233957.22,BRSMTOACNOR3,681,1151853,0.012268,0.58,2026-01-22,SAO MARTINHO SA,191488.49,BRSMTOACNOR3,636,1014056,0.013568,0.64,1.07
1,2026-05-06,PETR3,PETROLEO BRASILEIRO SA,7248588.31,BRPETRACNOR9,6926,35687337,0.380083,18.08,2026-01-22,PETROLEO BRASILEIRO SA,4448902.95,BRPETRACNOR9,6493,23559832,0.315226,14.90,1.07
0,2026-05-06,PETR4,PETROLEO BRASILEIRO SA,8612552.04,BRPETRACNPR6,8970,42402608,0.451604,21.48,2026-01-22,PETROLEO BRASILEIRO SA,5352039.39,BRPETRACNPR6,8440,28342527,0.379218,17.93,1.06
3,2026-05-06,BBDC4,BANCO BRADESCO SA,2385298.28,BRBBDCACNPR8,6094,11743658,0.125074,5.95,2026-01-22,BANCO BRADESCO SA,2211171.07,BRBBDCACNPR8,5768,11709588,0.156672,7.41,1.06
12,2026-05-06,JHSF3,JHSF PARTICIPACOES SA,534155.00,BRJHSFACNOR2,2074,2629832,0.028009,1.33,2026-01-22,JHSF PARTICIPACOES SA,341036.89,BRJHSFACNOR2,1989,1806012,0.024164,1.14,1.04
25,2026-05-06,CBAV3,CIA BRASILEIRA DE ALUMINI,236418.99,BRCBAVACNOR5,1093,1163973,0.012397,0.59,2026-01-22,CIA BRASILEIRA DE ALUMINI,176435.72,BRCBAVACNOR5,1062,934341,0.012501,0.59,1.03
7,2026-05-06,BBDC3,BANCO BRADESCO SA,855866.55,BRBBDCACNOR1,2532,4213730,0.044878,2.13,2026-01-22,BANCO BRADESCO SA,835809.41,BRBBDCACNOR1,2516,4426154,0.059221,2.80,1.01
5,2026-05-06,BBAS3,BANCO DO BRASIL SA,1487366.53,BRBBASACNOR3,3318,7322826,0.077991,3.71,2026-01-22,BANCO DO BRASIL SA,1771265.09,BRBBASACNOR3,4000,9380000,0.125503,5.93,0.83
47,2026-05-06,MYPK3,IOCHPE MAXION SA,85422.33,BRMYPKACNOR7,416,470408,0.004479,0.24,2026-01-22,IOCHPE MAXION SA,105908.99,BRMYPKACNOR7,535,560856,0.007504,0.35,0.78
46,2026-05-06,JBSS32,JBS NV,86960.01,BRJBSSBDR002,52,428134,0.004560,0.22,2026-01-22,JBS NV,164062.01,BRJBSSBDR002,107,868815,0.011625,0.55,0.49
67,2026-05-06,PINE13,BANCO PINE SA,0.00,BRPINEN03M16,0,0,0.000000,0.00,2026-01-22,BANCO PINE SA,0.00,BRPINEN03M16,0,0,0.000000,0.00,NaN

In [20]:
# new stocks
df_new_only = pd.merge(df_new, df_old, on="ticker", how='left', suffixes=('_new', '_old'), indicator=True)
df_new_only.loc[df_new_only['_merge'] == 'left_only'] \
    .sort_values(by='market_value_new', ascending=False)

,date_new,ticker,description_new,market_value_new,isin_new,shares_new,principal_new,weight%_new,weight_br%_new,date_old,description_old,market_value_old,isin_old,shares_old,principal_old,weight%_old,weight_br%_old,_merge
30,2026-05-06,EZTC3,EZ TEC EMPREENDIMENTOS E,180080.64,BREZTCACNOR0,620,886600,0.009443,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
31,2026-05-06,VAMO3,VAMOS LOCACAO DE CAMINHOE,179105.49,BRVAMOACNOR7,2199,881799,0.009391,0.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
40,2026-05-06,RIAA3,RIACHUELO,130936.05,BRRIAAACNOR2,637,644644,0.006866,0.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
45,2026-05-06,INTB3,INTELBRAS SA INDUSTRIA DE,110439.43,BRINTBACNOR9,388,508031,0.005791,0.26,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
57,2026-05-06,RANI3,IRANI PAPEL E EMBALAGEM S,62048.56,BRRANIACNOR5,388,305486,0.003254,0.15,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
60,2026-05-06,BLAU3,BLAU FARMACEUTICA SA,57806.57,BRBLAUACNOR8,269,284602,0.003031,0.14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
69,2026-05-06,SHUL4,SCHULZ SA,38175.23,BRSHULACNPR4,358,187950,0.002002,0.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
72,2026-05-06,ARML3,ARMAC LOCACAO LOGISTICA E,34396.09,BRARMLACNOR1,378,169344,0.001804,0.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
73,2026-05-06,CAML3,CAMIL ALIMENTOS SA,26353.60,BRCAMLACNOR3,199,129748,0.001382,0.07,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
75,2026-05-06,MATD3,HOSPITAL MATER DEI SA,9759.21,BRMATDACNOR4,84,48048,0.000512,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only
76,2026-05-06,SLCE3,SLC AGRICOLA SA,7129.29,BRSLCEACNOR2,20,35100,0.000374,0.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,left_only

In [21]:
# dropped stocks
df_old_only = pd.merge(df_new, df_old, on="ticker", how='right', suffixes=('_new', '_old'), indicator=True)
df_old_only.loc[df_old_only['_merge'] == 'right_only'] \
    .sort_values(by='market_value_old', ascending=False)

,date_new,ticker,description_new,market_value_new,isin_new,shares_new,principal_new,weight%_new,weight_br%_new,date_old,description_old,market_value_old,isin_old,shares_old,principal_old,weight%_old,weight_br%_old,_merge
41,NaN,RAPT4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-22,RANDON SA IMPLEMENTOS E P,93568.12,BRRAPTACNPR4,744,495504,0.006630,0.31,right_only
42,NaN,GUAR3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-22,GUARARAPES CONFECCOES SA,86958.16,BRGUARACNOR4,500,460500,0.006161,0.29,right_only
54,NaN,RAIZ4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-22,RAIZEN SA,45404.91,BRRAIZACNPR6,2968,240448,0.003217,0.15,right_only
62,NaN,ROMI3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-22,ROMI SA,35377.66,BRROMIACNOR8,227,187347,0.002507,0.12,right_only
70,NaN,ABCB2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-22,BANCO ABC BRASIL SA - RTS,1632.85,BRABCBD19PR1,14,8647,0.000116,0.01,right_only
72,NaN,PGMN1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2026-01-22,EMPREENDIMENTOS PAGUE-RTS,633.24,BRPGMND05OR4,48,3353,0.000045,0.00,right_only

In [22]:
df_merged.loc[df_merged['ticker'].str.contains('TAEE', na=False)]

Empty DataFrame
Columns: [date_new, ticker, description_new, market_value_new, isin_new, shares_new, principal_new, weight%_new, weight_br%_new, date_old, description_old, market_value_old, isin_old, shares_old, principal_old, weight%_old, weight_br%_old, share_ratio]
Index: []